const SUCCESS = 200;
const BAD_REQUEST = 400;
const INTERNAL_SERVER_ERROR = 500;
const NOT_FOUND = 404;
const NO_CONTENT =204;
const CREATED = 201;

export {SUCCESS, BAD_REQUEST,INTERNAL_SERVER_ERROR,NOT_FOUND,
        NO_CONTENT,CREATED};